"""empty message

Revision ID: 00399f51a4a9
Revises: 
Create Date: 2024-10-02 00:29:34.812227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00399f51a4a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('election_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'election', ['election_id'], ['id_election'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('election_id')

    # ### end Alembic commands ###
